config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", :locale => /uk/ do
    root to: "site#index"

    get "how-it-works", to: "site#how_it_works"
    get "role-by-role", to: "site#role_by_role"
    get "why-were-different", to: "site#why_different"
    get "customers", to: "site#customers"

    get "pricing", to: "site#pricing"
    get "contact-us", to: "site#contact"
    get "integrations", to: "integrations#index"

    get "try", to: "free_trial#index"
    post "try", to: "free_trial#create"

  	get "book_demo", to: "book_demo#index"
  	post "book_demo", to: "book_demo#create"

    get "poa", to: "poa#index"
    post "poa", to: "poa#create"

    get "/software/scheduling-software", to: "site#scheduling"
    get "/software/time-and-attendance", to: "site#attendance"
    get "/software/employee-app", to: "site#employee_app"
    get "/software/timeclock-app", to: "site#timeclock_app"
    get "/software/auto-scheduling", to: "site#auto_scheduling"
    get "/software/employee-onboarding", to: "site#employee_onboarding"
    get "/software/wage-and-hour-compliance", to: "site#compliance"
    get "/software/payroll-integration", to: "site#payroll"
    get "/software/employee-communications", to: "site#communications"

    get "/integrations/workday", to: "integrations#workday"

    get "/integrations/brightpay", to: "integrations#brightpay"
    get "/integrations/xero", to: "integrations#xero"
    get "/integrations/lightspeed", to: "integrations#lightspeed"
    get "/integrations/goodtill", to: "integrations#goodtill"
    get "/integrations/zettle", to: "integrations#zettle"
    get "/integrations/backofhouse", to: "integrations#back_of_house"
    get "/integrations/twicebaked", to: "integrations#twice_baked"
    get "/integrations/icr-touch", to: "integrations#icr_touch"
    get "/integrations/tenzo", to: "integrations#tenzo"
    get "/integrations/vitamojo", to: "integrations#vitamojo"

    get "/software/rota", to: "site#scheduling"

    get "/industry/hospitality", to: "site#hospitality"
    get "/industry/staffing", to: "site#staffing"

    # newly designed and relatively personalized
    get "/industry/restaurant-and-bars", to: "site#restaurants_and_bars"
    get "/industry/hospitals", to: "site#hospitals"
    get "/industry/call-centers", to: "site#call_centers"
    get "/industry/construction", to: "site#construction"
    get "/industry/elderly-care", to: "site#elder_care"
    get "/industry/healthcare", to: "site#healthcare"

    # all the same content bar the header
    get "/industry/hotels", to: "site#hotels"
    get "/industry/manufacturing", to: "site#manufacturing"
    get "/industry/retail", to: "site#retail"
    get "/industry/franchise", to: "site#franchise"

    get "/news", to: "news#index"
    get "/news/:slug", to: "news#article", as: "news_article"
    get "/whitepapers", to: "news#whitepapers"

    get "/privacy-policy", to: "site#privacy_policy"
    get "/terms", to: "site#terms"
    get "/cookies", to: "site#cookies_page"
    get "/security", to: "site#security"
    get "/biometric", to: "site#biometric"
    get "/gdpr", to: "site#gdpr"

    # old site redirects
    # (someone made a different url structure when redesigning pages,
    #  so there are duplicate urls that rank differently, which we have to maintain)
    get "industry/call-center/scheduling", to: "site#call_centers"
    get "industry/call-center/workforce-management", to: "site#call_centers"
    get "industry/hospitals/scheduling", to: "site#hospitals"
    get "industry/restaurant-and-dining", to: "site#restaurants_and_bars"
    get "industry/construction/scheduling", to: "site#construction"
    get "industry/elderly-care/scheduling", to: "site#elder_care"

    # the current page says pharmacy but is about medical practices. redirecting all for now.
    get "/industry/pharmacy" => redirect("/industry/healthcare")
    get "/industry/medical-and-pharmacy" => redirect("/industry/healthcare")

    get "/role/*slug" => redirect("/role-by-role")

    get "/software/labor-compliance" => redirect("/software/wage-and-hour-compliance")

    # these feature pages were deemed unimportant for SEO, so we don't need them immediately
    get "/software/leave-and-unavailability" => redirect("/how-it-works")
    get "/software/livewage-tracker" => redirect("/how-it-works")
    get "/software/shift-feedback" => redirect("/how-it-works")
    get "/software/shift-swapping" => redirect("/how-it-works")
    get "/software/chat" => redirect("/how-it-works")

    # Broken Link Redirect Fixs
    get 'eu/privacy-policy'=> redirect('uk/privacy-policy')
    get 'software/workforce-analytics' => redirect('/how-it-works')
    get 'software/labor-compliance' => redirect('/time-and-attendance')
    get 'tools/scheduling-template' => redirect('/scheduling-software')
    get '/uk/software/gps-clock-ins' => redirect('/how-it-works')
    get 'software/gps-clock-ins' => redirect('/how-it-works')
    get 'software' => redirect('/how-it-works')
    get 'subscribe' => redirect('/')

    get '/files/WORK03-Representative-contact-summary-2021.pdf' => redirect('/whitepapers')
    get '/uk/coookies' => redirect('/uk/cookies')
    get '/2016/12/08/scheduling-reform-pushes-way-retail-industry/' => redirect('/news')
    get '/2017/01/12/branding-building-relationships-and-getting-social/' => redirect('/news')
    get '/2017/01/17/workplace-legacy-barack-obama/' => redirect('/news')
    get '/2018/01/22/recruiting-tech-expanding-unlike-recruiters-willingness-use/' => redirect('/news')
    get '/2018/06/15/artificial-in...utomation-and-the-future-of-talent-acquisition/' => redirect('/news')
    get '/2018/08/14/protecting-yo...eing-omarosad-workplace-recordings-and-the-law/' => redirect('/news')
    get '/2018/08/21/workplace-mon...ng-corporate-privacy-versus-individual-privacy/' => redirect('/news')
    get '/2018/09/26/dont-ignore-state-law-when-considering-wage-and-hour-issues/' => redirect('/news')
    get '/2018/10/03/predictable-shift-laws-spread-more-cities-states/' => redirect('/news')
    get '/2018/11/09/meet-new-colleague-artificial-intelligence/' => redirect('/news')
    get '/2018/12/12/hot-topics-for-2019-metoo-and-data-privacy/' => redirect('/news')
    get '/2019/08/07/the-ethics-of-artificial-intelligence-in-the-workplace/' => redirect('/news')
    get '/2019/11/06/human-capital-disclosure-may-soon-be-mandated-by-the-sec/' => redirect('/news')
    get '/files/WORK03-Representative-contact-summary-2021.pdf' => redirect('/whitepapers')
    get '/news/give-managers-the-t...they-need-to-sharpen-up-their-all-around-skills' => redirect('/news')
    get '/scheduling-software' => redirect('/software/scheduling-software')
    #DELETE AFTER VIDEOS PAGE ADDED
    get '/videos/armen-berjikly-na...communication-advances-artificial-intelligence/' => redirect('/news')
    get '/videos/watch/great-workforce-management-starts-here-id=0yt=0' => redirect('/news')
    get '/videos/watch/this-is-workforcecom-id=3yt=0' => redirect('/news')
    get '/videos/watch/two-week-implementation--workforcecom-id=4yt=0' => redirect('/news')
    
  end

  # sitemaps available from public folder at
  # /sitemap.xml
  # /uk_sitemap.xml
  # /news_sitemap.xml

  #Error Pages
  match("*path", via: :all, to: "errors#not_found")
  get("/404" => "errors#not_found")
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  include RegionHelper

  # core pages
  def index
  end

  def how_it_works
  end

  def role_by_role
  end

  def before_and_after
  end

  def why_different
  end

  def customers
  end

  def pricing
  end

  def contact
  end

  # seo pages
  def scheduling
    if uk? && request.path.include?("/software/scheduling-software")
      return redirect_to(software_rota_path(locale: "uk"), status: :moved_permanently)
    end

    if us? && request.path.include?("/software/rota")
      return redirect_to(software_rota_path(locale: "uk"), status: :moved_permanently)
    end

    @canonical = "/software/scheduling-software"
    @uk_alternate = "/uk/software/rota"
    @us_alternate = "/software/scheduling-software"
  end

  def attendance
  end

  def employee_app
  end

  def timeclock_app
  end

  def employee_onboarding
  end

  def compliance
  end

  def payroll
  end

  def communications
  end

  def hospitality
  end

  def staffing
  end

  def restaurants_and_bars
  end

  def hospitals
  end

  def call_centers
  end

  def construction
  end

  def elder_care
  end

  def healthcare
  end

  def hotels
  end

  def manufacturing
  end

  def retail
  end

  def franchise
  end

  # footer pages
  def privacy_policy
    if uk?
      render "privacy_policy_uk"
    else
      render "privacy_policy"
    end
  end

  def cookies_page
  end
  
  def terms
    if uk?
      render "terms_uk"
    else
      render "terms_us"
    end
  end

  def security
  end

  def biometric
  end

  def gdpr
  end
end

app/helpers/site_helper.rb
module SiteHelper
	def excerpt(post, length)
		post = sanitize(post)
		if post.length < length
			post
		else
			post[0..length-1] << "..."
		end
	end
end

app/views/site/contact.html.erb
<% content_for :title do %>
  Get in touch
<% end %>

<% content_for :description do %>
 Contact Workforce.com the #1 platform for scheduling, clocking in & out, time off, and compliance with employment law. Perfect for businesses with hourly workers.
<% end %>

<div data-controller="demo-modal">
  <div class="bg-white">
    <div class="relative overflow-hidden">
      <div class="absolute inset-y-0 h-full w-full" aria-hidden="true">
        <div class="relative h-full">

          <svg class="absolute right-full transform translate-y-1/3 translate-x-1/4 md:translate-y-1/2 sm:translate-x-1/2 lg:translate-x-full" width="404" height="784" fill="none" viewBox="0 0 404 784">
            <defs>
              <pattern id="e229dbec-10e9-49ee-8ec3-0286ca089edf" x="0" y="0" width="20" height="20" patternUnits="userSpaceOnUse">
                <circle cx="1.5" cy="1.5" r="1.5" class="text-gray-200" fill="currentColor" />
              </pattern>
            </defs>
            <rect width="404" height="784" fill="url(#e229dbec-10e9-49ee-8ec3-0286ca089edf)" />
          </svg>
          <svg class="absolute left-full transform -translate-y-3/4 -translate-x-1/4 sm:-translate-x-1/2 md:-translate-y-1/2 lg:-translate-x-3/4" width="404" height="784" fill="none" viewBox="0 0 404 784">
            <defs>
              <pattern id="d2a68204-c383-44b1-b99f-42ccff4e5365" x="0" y="0" width="20" height="20" patternUnits="userSpaceOnUse">
                <circle cx="1.5" cy="1.5" r="1.5" class="text-gray-200" fill="currentColor" />
              </pattern>
            </defs>
            <rect width="404" height="784" fill="url(#d2a68204-c383-44b1-b99f-42ccff4e5365)" />
          </svg>
        </div>
      </div>
      <div class="relative pt-6 pb-10 sm:pb-6 2xl:pb-10">
        <%= render "layouts/nav" %>
        <div class="mt-16 sm:mb-20 mx-auto max-w-5xl px-4 sm:mt-24 sm:px-0 2xl:mb-8 text-center">
          <div class="text-center">
            <h1 class="text-6xl tracking-tight font-extrabold text-gray-900 sm:text-6xl md:text-9xl max-w-5xl mx-auto">
              <span class="block">Get in touch</span></span>
            </h1>
          </div>          
          <p class="mx-auto mt-3 text-center text-xl sm:text-2xl text-gray-700 sm:text-lg md:mt-5 md:text-2xl max-w-4xl">
            Got a question? Call us, email us, or schedule a time to chat below.
          </p>
          <div class="w-max bg-gray-50 rounded-lg py-5 px-6 mx-auto mt-10 mb-20">
            <div class="flex flex-col space-y-4 sm:space-y-0 sm:flex-row sm:space-x-10 text-gray-600">
              <div class="flex flex-col items-start">
                <% if uk? %>
                  <p class="text-base sm:text-lg">WeWork, 1 Mark Square</p>
                  <p class="text-base sm:text-lg">London EC2A 4EG</p>
                <% else %>
                  <p class="text-base sm:text-lg">150 N. Michigan Ave</p>
                  <p class="text-base sm:text-lg">Chicago, IL 60601</p>
                <% end %>
              </div>
              <div class="flex flex-col items-start">
                <% if uk? %>
                  <%= link_to "+44 333 577 2373 →", "tel:+44 333 577 2373", class: "text-base sm:text-lg hover:text-blue-tertiary" %>
                <% else %>
                  <%= link_to "888 766 5582 →", "tel:888 766 5582", class: "text-base sm:text-lg hover:text-blue-tertiary" %>
                <% end %>
                <%= link_to "support@workforce.com →", "mailto:support@workforce.com", class: "text-base sm:text-lg hover:text-blue-tertiary" %>
              </div>
            </div>
          </div>
          <div class="flex flex-col md:flex-row items-center justify-center md:space-x-4 space-y-4 md:space-y-0 mt-8 mb-6">
            <div class="btn-green px-8 py-2 mx-0 inline-flex space-x-2 items-center justify-center" data-action="click->demo-modal#open">
              <%= render "layouts/phone" %>
              <span>Book a call</span>
            </div>
            <%= link_to "Try Workforce.com today", try_path, class: "btn-blue-secondary mt-8 mb-6 px-8 py-2 mx-auto" %>
          </div>
        </div>
      </div>

      <div class="relative -mb-32 lg:-mb-40 2xl:-mb-60">
        <div class="relative inset-0 flex flex-col h-52 sm:h-72 2xl:h-96" aria-hidden="true">
          <div class="h-24 sm:flex-1 w-full bg-gray-wave">
          </div>
        </div>
      </div>

      <div class="relative bg-gray-50">
        <div class="max-w-3xl mx-auto px-4 sm:px-6 pb-32">
          <div class="pt-20 relative text-center">
            <h2 class="text-center text-3xl text-gray-800 text-opacity-90 font-extrabold tracking-tight sm:text-5xl">
              <%= link_to "Learn about how it works", how_it_works_path, class: "underline" %>, <%= link_to "see the benefits based on role", role_by_role_path, class: "underline" %>, or if you're ready to get started —
            </h2>
            <div class="flex flex-col md:flex-row items-center justify-center md:space-x-4 space-y-4 md:space-y-0 mt-8 mb-6">
              <div class="btn-green px-8 py-2 mx-0 inline-flex space-x-2 items-center justify-center" data-action="click->demo-modal#open">
                <%= render "layouts/phone" %>
                <span>Book a call</span>
              </div>
              <%= link_to "Try Workforce.com today", try_path, class: "btn-blue-secondary mt-8 mb-6 px-8 py-2 mx-auto" %>
            </div>
          </div>
        </div>
      </div>
    </div> 
  </div>
  <%= render "layouts/demo_modal" %>
</div>

app/views/site/hotels.html.erb
<% content_for :title do %>
  Scheduling Software for Hotels & Hospitality
<% end %>

<% content_for :description do %>
  Workforce.com helps you manage hotel employee by creating staff schedules with Employee Scheduling Software, paying them correctly minus complexity with Payroll Integrations and more! Sign up for a free trial now.
<% end %>

<div data-controller="demo-modal">
  <div class="bg-white">
    <div class="relative overflow-hidden">
      <div class="absolute inset-y-0 h-full w-full" aria-hidden="true">
        <div class="relative h-full">
          <svg class="absolute right-full transform translate-y-1/3 translate-x-1/4 md:translate-y-1/2 sm:translate-x-1/2 lg:translate-x-full" width="404" height="784" fill="none" viewBox="0 0 404 784">
            <defs>
              <pattern id="e229dbec-10e9-49ee-8ec3-0286ca089edf" x="0" y="0" width="20" height="20" patternUnits="userSpaceOnUse">
                <circle cx="1.5" cy="1.5" r="1.5" class="text-gray-200" fill="currentColor" />
              </pattern>
            </defs>
            <rect width="404" height="784" fill="url(#e229dbec-10e9-49ee-8ec3-0286ca089edf)" />
          </svg>
          <svg class="absolute left-full transform -translate-y-3/4 -translate-x-1/4 sm:-translate-x-1/2 md:-translate-y-1/2 lg:-translate-x-3/4" width="404" height="784" fill="none" viewBox="0 0 404 784">
            <defs>
              <pattern id="d2a68204-c383-44b1-b99f-42ccff4e5365" x="0" y="0" width="20" height="20" patternUnits="userSpaceOnUse">
                <circle cx="1.5" cy="1.5" r="1.5" class="text-gray-200" fill="currentColor" />
              </pattern>
            </defs>
            <rect width="404" height="784" fill="url(#d2a68204-c383-44b1-b99f-42ccff4e5365)" />
          </svg>
        </div>
      </div>
      <div class="relative pt-6 pb-10 sm:pb-6 2xl:pb-10">
        <%= render "layouts/nav" %>
        <div class="flex flex-col sm:flex-row space-y-12 sm:space-y-0 sm:space-x-20 mt-16 mx-auto max-w-7xl px-4 sm:mt-24 sm:px-6 justify-center">
          <div class="sm:w-2/6 relative flex items-center">
            <div class="relative w-full h-full pt-32 sm:pt-64 pb-10 rounded-2xl shadow-xl overflow-hidden">
              <%= image_tag("hotels-header.jpg", class: "absolute inset-0 h-full w-full object-cover") %>
            </div>
          </div>
          <div class="text-left sm:w-1/2 flex flex-col justify-center">
            <span class="relative block uppercase mb-3 text-gray-400">Scheduling Software for Hotels & Hospitality</span>
            <h1 class="text-4xl tracking-tight font-extrabold text-gray-900 sm:text-5xl md:text-6xl">
              <span class="block">Keep service consistent with <span class="text-blue-tertiary">quick scheduling</span> and <%= labor %> forecasting.</span>
            </h1>
            <p class="mt-3 text-xl text-gray-700 sm:text-lg md:mt-5 md:text-1.5xl max-w-3xl">
              Frontline managers shouldn’t be spending hours on schedule changes and admin work. Use live wage insights to make <%= labor %> decisions before incurring spend, and quickly fill shifts as needed.
            </p>
            <div class="inline-flex flex-col md:flex-row my-5 md:space-x-4 space-y-4 md:space-y-0">
              <div class="btn-green-action flex w-max items-center space-x-2" data-action="click->demo-modal#open">
                <%= render "layouts/phone" %>
                <span>Book a call</span>
              </div>
              <%= link_to "Create free account", try_path, class: "btn-blue-secondary px-8 py-2 w-max bg-white" %>
            </div>
          </div>
        </div>
      </div>
      <div class="relative -mb-2">
        <div class="relative inset-0 flex flex-col h-20 sm:h-72 2xl:h-96" aria-hidden="true">
          <div class="flex-1 w-full bg-gray-wave">
          </div>
        </div>
      </div>

      <div class="relative py-8 sm:py-10 sm:pt-8 bg-gray-50 -mt-12 sm:-mt-48 2xl:-mt-72">
        <div class="flex flex-col-reverse sm:grid gap-10 grid-cols-6 lg:grid-cols-12 max-w-6xl mx-auto px-4 sm:mt-12 sm:px-6">
          <div class="col-span-6 text-left flex flex-col justify-center">
            <h2 class="relative text-2.5xl leading-8 text-gray-800 font-extrabold tracking-tight sm:text-5xl z-10">
              Take the guesswork out of <%= labor %> forecasting.</span>
            </h2>
            <ul class="ml-8 my-6 space-y-2">
              <li>
                <span class="absolute -ml-8 my-1 p-1 w-7">
                  <%= image_tag("everything-icon1.png") %>
                </span>
                <p class="px-2 text-lg sm:text-xl md:text-1.5xl text-gray-500 pb-2">Optimize your schedules according to historical data and see costs per team, per week, or per location in real time.</p>
              </li>
              <li>
                <span class="absolute -ml-8 my-1 p-1 w-7">
                  <%= image_tag("everything-icon2.png") %>
                </span>
                <p class="px-2 text-lg sm:text-xl md:text-1.5xl text-gray-500 pb-2">Equip frontline managers to make cost-saving decisions with wage costs shown in real-time.</p>
              </li>
              <li>
                <span class="absolute -ml-8 my-1 p-1 w-7">
                  <%= image_tag("everything-icon3.png") %>
                </span>
                <p class="px-2 text-lg sm:text-xl md:text-1.5xl text-gray-500 pb-2">Spot unnecessary overtime hours and adjust employee schedules quickly.</p>
              </li>
            </ul>
          </div>
          <div class="col-span-6 relative sm:pl-10 items-center flex sm:mb-12">
            <%= link_to software_scheduling_software_path do%>
            <div class="z-20 transform rotate-1">
              <%= image_tag("scheduling-header.png") %>
            </div>
            <% end %>
          </div>
        </div>
      </div>

      <div class="relative py-8 sm:py-10 sm:pt-16 bg-white">
        <div class="grid gap-10 lg:grid-cols-12 max-w-6xl mx-auto px-4 sm:mt-12 sm:px-6">
          <div class="col-span-6 relative sm:pr-10 items-center flex sm:mb-12">
          <%= link_to software_scheduling_software_path do%>
            <div class="z-20 transform -rotate-1">
              <%= image_tag("shift-swaps-that-saves-money.png") %>
            </div>
          <% end %>
          </div>
          <div class="col-span-6 text-left">
            <h2 class="relative text-2.5xl leading-8 text-gray-800 font-extrabold tracking-tight sm:text-5xl z-10">
              Fill open shifts and keep costs under control.</span>
            </h2>
            <ul class="ml-8 my-6 space-y-2">
              <li>
                <span class="absolute -ml-8 my-1 p-1 w-7">
                  <%= image_tag("easily-icon1.png") %>
                </span>
                <p class="px-2 text-lg sm:text-xl md:text-1.5xl text-gray-500 pb-2">Choose to broadcast the shift to all available staff or offer it to select employees.</p>
              </li>
              <li>
                <span class="absolute -ml-8 my-1 p-1 w-7">
                  <%= image_tag("easily-icon2.png") %>
                </span>
                <p class="px-2 text-lg sm:text-xl md:text-1.5xl text-gray-500 pb-2">Get notified when an employee who offers to fill a shift is about to go into overtime.</p>
              </li>
              <li>
                <span class="absolute -ml-8 my-1 p-1 w-7">
                  <%= image_tag("easily-icon3.png") %>
                </span>
                <p class="px-2 text-lg sm:text-xl md:text-1.5xl text-gray-500 pb-2">See the cost of potential swaps and see to it that you stay within budget.</p>
              </li>
            </ul>
          </div>
        </div>
      </div>

      <div class="relative py-8 sm:py-10 sm:pt-8 bg-white">
        <div class="flex flex-col-reverse sm:grid gap-10 grid-cols-6 lg:grid-cols-12 max-w-6xl mx-auto px-4 sm:mt-12 sm:px-6">
          <div class="col-span-6 text-left flex flex-col justify-center">
            <h2 class="relative text-2.5xl leading-8 text-gray-800 font-extrabold tracking-tight sm:text-5xl z-10 -mr-6">
              Get deeper insights with easy-to-generate reports.</span>
            </h2>
            <ul class="ml-8 my-6 space-y-2">
              <li>
                <span class="absolute -ml-8 my-1 p-1 w-7">
                  <%= image_tag("get-deeper-icon1.png") %>
                </span>
                <p class="px-2 text-lg sm:text-xl md:text-1.5xl text-gray-500 pb-2">Identify trends and potential issues in your operations using ready-made report templates. Or design your own reports around the metrics most important to you.</p>
              </li>
              <li>
                <span class="absolute -ml-8 my-1 p-1 w-7">
                  <%= image_tag("get-deeper-icon2.png") %>
                </span>
                <p class="px-2 text-lg sm:text-xl md:text-1.5xl text-gray-500 pb-2">Use reporting insights to find the best times for employee training and development.</p>
              </li>
            </ul>
          </div>
          <div class="col-span-6 relative sm:pl-10 items-center flex sm:mb-12">
            <%= link_to software_scheduling_software_path do%>
            <div class="z-20 transform rotate-1">
              <%= image_tag("get-deeper.png") %>
            </div>
            <% end %>
          </div>
        </div>
      </div>

      <div class="relative py-8 sm:py-10 sm:pt-16 bg-gray-50">
        <div class="grid gap-10 lg:grid-cols-12 max-w-6xl mx-auto px-4 sm:mt-12 sm:px-6">
          <div class="col-span-6 relative sm:pr-10 items-center justify-center flex sm:mb-12">
            <%= link_to software_employee_app_path do%>
            <div class="z-20 transform -rotate-1">
              <%= image_tag("shift-communication.png") %>
            </div>
            <% end %>
          </div>
          <div class="col-span-6 text-left">
            <h2 class="relative text-2.5xl leading-8 text-gray-800 font-extrabold tracking-tight sm:text-5xl z-10 -mr-6">
              All in the palm of your hand.</span>
            </h2>
            <p class="text-lg sm:text-xl md:text-1.5xl text-gray-500 pt-6">Whether you need to replace unavailable staff, edit their shift times, or check who’s working where, the Employee Scheduling App has you covered.</p>
            <ul class="ml-8 my-6 space-y-2">
              <li>
                <span class="absolute -ml-8 my-1 p-1 w-7">
                  <%= image_tag("easily-address-icon2.png") %>
                </span>
                <p class="px-2 text-lg sm:text-xl md:text-1.5xl text-gray-500 pb-2">Managers don’t have to be stuck in the back room. With their mobile devices, they can manage schedules, approve leaves, and offer shift swaps.</p>
              </li>
              <li>
                <span class="absolute -ml-8 my-1 p-1 w-7">
                  <%= image_tag("easily-address-icon3.png") %>
                </span>
                <p class="px-2 text-lg sm:text-xl md:text-1.5xl text-gray-500 pb-2">Certain schedules staying consistent over time? Create templates or simply copy and paste to succeeding weeks or periods.</p>
              </li>
            </ul>
          </div>
        </div>
      </div>

      <div class="relative py-8 sm:py-10 sm:pt-8 bg-white">
        <div class="grid sm:gap-10 lg:grid-cols-12 max-w-7xl mx-auto px-4 mt-12 sm:px-6">
          <div class="col-span-6 text-left flex flex-col justify-center">
            <h2 class="relative text-4xl text-gray-800 font-extrabold tracking-tight sm:text-5xl z-10 -mr-6">
              Integrate with your POS, payroll, and HR systems</span>
            </h2>
            <div class="mt-8 mb-2 sm:my-8 space-y-2">
              <p class="text-lg sm:text-xl md:text-1.5xl text-gray-500">Integrate your current tools with our system for faster, more efficient workforce management operations, while providing robust scheduling & attendance for frontline teams.</p>
            </div>
          </div>
          <div class="col-span-6 relative sm:pl-10 items-center flex sm:mb-12">
          <%= link_to software_payroll_integration_path do %>
            <div class="z-20">
              <%= image_tag("integrations.png") %>
            </div>
          <% end %>
          </div>
        </div>
      </div>

      <div class="relative bg-white">
        <div class="max-w-3xl mx-auto px-4 sm:px-6 pb-16">
          <div class="pt-20 relative text-center">
            <h2 class="text-center text-3xl text-gray-800 text-opacity-90 font-extrabold tracking-tight sm:text-5xl">
              <%= link_to "Learn about how it works", how_it_works_path, class: "underline" %>, <%= link_to "see how customers felt before & after", why_were_different_path, class: "underline" %>, or if you're ready to get started —
            </h2>
            <div class="flex flex-col md:flex-row items-center justify-center md:space-x-4 space-y-4 md:space-y-0 mt-8 mb-6">
              <div class="btn-green px-8 py-2 mx-0 inline-flex space-x-2 items-center justify-center" data-action="click->demo-modal#open">
                <%= render "layouts/phone" %>
                <span>Book a call</span>
              </div>
              <%= link_to "Try Workforce.com today", try_path, class: "btn-blue-secondary mt-8 mb-6 px-8 py-2 mx-auto" %>
            </div>
          </div>
        </div>
      </div>
    </div> 
  </div>
  <%= render "layouts/demo_modal" %>
</div>