config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", :locale => /uk/ do
    root to: "site#index"

    get "how-it-works", to: "site#how_it_works"
    get "role-by-role", to: "site#role_by_role"
    get "why-were-different", to: "site#why_different"
    get "customers", to: "site#customers"

    get "pricing", to: "site#pricing"
    get "contact-us", to: "site#contact"
    get "integrations", to: "integrations#index"

    get "try", to: "free_trial#index"
    post "try", to: "free_trial#create"

  	get "book_demo", to: "book_demo#index"
  	post "book_demo", to: "book_demo#create"

    get "poa", to: "poa#index"
    post "poa", to: "poa#create"

    get "/software/scheduling-software", to: "site#scheduling"
    get "/software/time-and-attendance", to: "site#attendance"
    get "/software/employee-app", to: "site#employee_app"
    get "/software/timeclock-app", to: "site#timeclock_app"
    get "/software/auto-scheduling", to: "site#auto_scheduling"
    get "/software/employee-onboarding", to: "site#employee_onboarding"
    get "/software/wage-and-hour-compliance", to: "site#compliance"
    get "/software/payroll-integration", to: "site#payroll"
    get "/software/employee-communications", to: "site#communications"

    get "/integrations/workday", to: "integrations#workday"

    get "/integrations/brightpay", to: "integrations#brightpay"
    get "/integrations/xero", to: "integrations#xero"
    get "/integrations/lightspeed", to: "integrations#lightspeed"
    get "/integrations/goodtill", to: "integrations#goodtill"
    get "/integrations/zettle", to: "integrations#zettle"
    get "/integrations/backofhouse", to: "integrations#back_of_house"
    get "/integrations/twicebaked", to: "integrations#twice_baked"
    get "/integrations/icr-touch", to: "integrations#icr_touch"
    get "/integrations/tenzo", to: "integrations#tenzo"
    get "/integrations/vitamojo", to: "integrations#vitamojo"

    get "/software/rota", to: "site#scheduling"

    get "/industry/hospitality", to: "site#hospitality"
    get "/industry/staffing", to: "site#staffing"

    # newly designed and relatively personalized
    get "/industry/restaurant-and-bars", to: "site#restaurants_and_bars"
    get "/industry/hospitals", to: "site#hospitals"
    get "/industry/call-centers", to: "site#call_centers"
    get "/industry/construction", to: "site#construction"
    get "/industry/elderly-care", to: "site#elder_care"
    get "/industry/healthcare", to: "site#healthcare"

    # all the same content bar the header
    get "/industry/hotels", to: "site#hotels"
    get "/industry/manufacturing", to: "site#manufacturing"
    get "/industry/retail", to: "site#retail"
    get "/industry/franchise", to: "site#franchise"

    get "/news", to: "news#index"
    get "/news/:slug", to: "news#article", as: "news_article"
    get "/whitepapers", to: "news#whitepapers"

    get "/privacy-policy", to: "site#privacy_policy"
    get "/terms", to: "site#terms"
    get "/cookies", to: "site#cookies_page"
    get "/security", to: "site#security"
    get "/biometric", to: "site#biometric"
    get "/gdpr", to: "site#gdpr"

    # old site redirects
    # (someone made a different url structure when redesigning pages,
    #  so there are duplicate urls that rank differently, which we have to maintain)
    get "industry/call-center/scheduling", to: "site#call_centers"
    get "industry/call-center/workforce-management", to: "site#call_centers"
    get "industry/hospitals/scheduling", to: "site#hospitals"
    get "industry/restaurant-and-dining", to: "site#restaurants_and_bars"
    get "industry/construction/scheduling", to: "site#construction"
    get "industry/elderly-care/scheduling", to: "site#elder_care"

    # the current page says pharmacy but is about medical practices. redirecting all for now.
    get "/industry/pharmacy" => redirect("/industry/healthcare")
    get "/industry/medical-and-pharmacy" => redirect("/industry/healthcare")

    get "/role/*slug" => redirect("/role-by-role")

    get "/software/labor-compliance" => redirect("/software/wage-and-hour-compliance")

    # these feature pages were deemed unimportant for SEO, so we don't need them immediately
    get "/software/leave-and-unavailability" => redirect("/how-it-works")
    get "/software/livewage-tracker" => redirect("/how-it-works")
    get "/software/shift-feedback" => redirect("/how-it-works")
    get "/software/shift-swapping" => redirect("/how-it-works")
    get "/software/chat" => redirect("/how-it-works")

    # Broken Link Redirect Fixs
    get 'eu/privacy-policy'=> redirect('uk/privacy-policy')
    get 'software/workforce-analytics' => redirect('/how-it-works')
    get 'software/labor-compliance' => redirect('/time-and-attendance')
    get 'tools/scheduling-template' => redirect('/scheduling-software')
    get '/uk/software/gps-clock-ins' => redirect('/how-it-works')
    get 'software/gps-clock-ins' => redirect('/how-it-works')
    get 'software' => redirect('/how-it-works')
    get 'subscribe' => redirect('/')

    get '/files/WORK03-Representative-contact-summary-2021.pdf' => redirect('/whitepapers')
    get '/uk/coookies' => redirect('/uk/cookies')
    get '/2016/12/08/scheduling-reform-pushes-way-retail-industry/' => redirect('/news')
    get '/2017/01/12/branding-building-relationships-and-getting-social/' => redirect('/news')
    get '/2017/01/17/workplace-legacy-barack-obama/' => redirect('/news')
    get '/2018/01/22/recruiting-tech-expanding-unlike-recruiters-willingness-use/' => redirect('/news')
    get '/2018/06/15/artificial-in...utomation-and-the-future-of-talent-acquisition/' => redirect('/news')
    get '/2018/08/14/protecting-yo...eing-omarosad-workplace-recordings-and-the-law/' => redirect('/news')
    get '/2018/08/21/workplace-mon...ng-corporate-privacy-versus-individual-privacy/' => redirect('/news')
    get '/2018/09/26/dont-ignore-state-law-when-considering-wage-and-hour-issues/' => redirect('/news')
    get '/2018/10/03/predictable-shift-laws-spread-more-cities-states/' => redirect('/news')
    get '/2018/11/09/meet-new-colleague-artificial-intelligence/' => redirect('/news')
    get '/2018/12/12/hot-topics-for-2019-metoo-and-data-privacy/' => redirect('/news')
    get '/2019/08/07/the-ethics-of-artificial-intelligence-in-the-workplace/' => redirect('/news')
    get '/2019/11/06/human-capital-disclosure-may-soon-be-mandated-by-the-sec/' => redirect('/news')
    get '/files/WORK03-Representative-contact-summary-2021.pdf' => redirect('/whitepapers')
    get '/news/give-managers-the-t...they-need-to-sharpen-up-their-all-around-skills' => redirect('/news')
    get '/scheduling-software' => redirect('/software/scheduling-software')
    #DELETE AFTER VIDEOS PAGE ADDED
    get '/videos/armen-berjikly-na...communication-advances-artificial-intelligence/' => redirect('/news')
    get '/videos/watch/great-workforce-management-starts-here-id=0yt=0' => redirect('/news')
    get '/videos/watch/this-is-workforcecom-id=3yt=0' => redirect('/news')
    get '/videos/watch/two-week-implementation--workforcecom-id=4yt=0' => redirect('/news')
    
  end

  # sitemaps available from public folder at
  # /sitemap.xml
  # /uk_sitemap.xml
  # /news_sitemap.xml

  #Error Pages
  match("*path", via: :all, to: "errors#not_found")
  get("/404" => "errors#not_found")
end

app/views/layouts/_bg_gradient.html.erb
<svg xmlns="http://www.w3.org/2000/svg" width="375" height="334" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M404.438 38.895S25.458-59.199-53.402 57.04C-132.26 173.278-29.913 275.147-18.061 313c11.852 37.853 115-3 227 3s195.5 17.9 195.5 17.9V38.895z" fill="url(#paint0_linear)"/><defs><linearGradient id="paint0_linear" x1="-83" y1="-67.202" x2="404.438" y2="-67.202" gradientUnits="userSpaceOnUse"><stop stop-color="#48b7da"/><stop offset="1" stop-color="#3c98c9"/></linearGradient></defs></svg>

app/views/layouts/_camera.html.erb
<svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
  <path d="M2 6a2 2 0 012-2h6a2 2 0 012 2v8a2 2 0 01-2 2H4a2 2 0 01-2-2V6zM14.553 7.106A1 1 0 0014 8v4a1 1 0 00.553.894l2 1A1 1 0 0018 13V7a1 1 0 00-1.447-.894l-2 1z" />
</svg>

app/views/layouts/_cross_region_redirect.html.erb
<% if unknown_region? %>
  <script>
    (function () {
      const tz = Intl.DateTimeFormat().resolvedOptions().timeZone
      if (tz.match(/Europe/g)) {
        window.location.replace("<%= url_for(_routes.recognize_path(request.path).merge(locale: "uk")) %>")
      }
      if (tz.match(/Australia/g) && window.location.pathname !== "/security" && window.location.pathname !== "/gdpr") {
        window.location.replace("https://www.tanda.co")
      }
    })()
  </script>
<% end %>

app/views/layouts/_demo_modal.html.erb
<% booking_type = :call if local_assigns[:booking_type].nil? %>
<div class="fixed text-gray-500 flex items-center justify-center overflow-auto z-50 bg-black bg-opacity-40 left-0 right-0 top-0 bottom-0 hidden" data-demo-modal-target="bg" data-transition-enter="transition ease-out duration-300" data-transition-enter-start="transform opacity-0" data-transition-enter-end="transform opacity-100" data-transition-leave="z-30 transition ease-in duration-200" data-transition-leave-start="transform opacity-100" data-transition-leave-end="transform opacity-0 z-0" data-action="click->demo-modal#close">
  <div class="bg-white rounded-xl shadow-2xl p-6 sm:p-12 py-16 sm:py-20 sm:w-2/5 mx-3 sm:mx-10" data-demo-modal-target="panel" data-transition-enter="transition ease-out duration-300" data-transition-enter-start="transform opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95" data-transition-enter-end="transform opacity-100 translate-y-0 sm:scale-100" data-transition-leave="transition ease-in duration-200" data-transition-leave-start="transform opacity-100 translate-y-0 sm:scale-100" data-transition-leave-end="transform z-0 opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95">
	<%= turbo_frame_tag "book_demo", src: book_demo_path(type: booking_type), loading: "lazy" %>
  </div>
</div>

app/views/layouts/_drawn_down_arrow.html.erb
<svg class="<%= custom_class %>" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" x="0px" y="0px" viewBox="0 0 100 100" xml:space="preserve">
	<path d="M82.06,21.54c-0.65-1.93-2.53-1.41-3.79-0.42C53.61,40.5,29.92,61.09,7.28,82.81c-1.34,1.28-2.77,3.55-2.12,5.5  c0.61,1.81,2.6,1.56,3.79,0.42c22.64-21.71,46.33-42.31,70.99-61.7C81.37,25.91,82.67,23.37,82.06,21.54z"/>
	<path d="M84.5,10.72c-3.36,0.47-6.7,1.14-9.99,1.98c-6.53,1.67-12.85,4.08-18.9,7.04c-1.74,0.85-3.11,3.29-3.01,5.21  c0.1,1.89,1.46,2.62,3.13,1.8c4.64-2.27,9.43-4.15,14.39-5.6c4.72-1.38,10.03-2.92,14.98-2.99c1.53-0.02,3.88,0.09,3.69,2.07  c-0.1,1.05-1.16,2.45-1.63,3.37c-0.56,1.08-1.12,2.16-1.69,3.24c-2.54,4.76-5.26,9.41-8.14,13.98c-0.79,1.25-1.55,4.01,0.08,4.96  c1.71,0.98,3.58-1.2,4.34-2.41c3.71-5.89,7.16-11.93,10.3-18.14c2.1-4.15,5.7-11.81-0.58-14.28C89.24,10.06,86.81,10.4,84.5,10.72z"/>
</svg>

app/views/layouts/_footer.html.erb
<footer class="bg-white" aria-labelledby="footerHeading">
  <h2 id="footerHeading" class="sr-only">Footer</h2>
  <div class="max-w-7xl mx-auto py-12 px-4 sm:px-6 lg:py-16 lg:px-8">
    <div class="xl:grid xl:grid-cols-2 xl:gap-8">
      <div class="grid grid-cols-2 gap-8 xl:col-span-2">
        <div class="md:grid md:grid-cols-2 md:gap-8">
          <div>
            <h3 class="text-sm font-semibold text-gray-400 tracking-wider uppercase">
              Product
            </h3>
            <ul class="mt-4 space-y-4">
              <li>
                <% if uk? %>
                  <%= link_to "Employee Rota Software", software_rota_path, class: "text-base text-gray-500 hover:text-gray-900" %>
                <% else %>
                  <%= link_to "Employee Scheduling", software_scheduling_software_path, class: "text-base text-gray-500 hover:text-gray-900" %>
                <% end %>
              </li>
              <li>
                <%= link_to "Time & Attendance", software_time_and_attendance_path, class: "text-base text-gray-500 hover:text-gray-900" %>
              </li>
              <li>
                <%= link_to "Payroll Integration", software_payroll_integration_path, class: "text-base text-gray-500 hover:text-gray-900" %>
              </li>
              <li>
                <%= link_to "Employee App", software_employee_app_path, class: "text-base text-gray-500 hover:text-gray-900" %>
              </li>
              <li>
                <%= link_to "Paperless Onboarding", software_employee_onboarding_path, class: "text-base text-gray-500 hover:text-gray-900" %>
              </li>
              <li>
                <%= link_to "Communications", software_employee_communications_path, class: "text-base text-gray-500 hover:text-gray-900" %>
              </li>
              <li>
                <%= link_to "Auto Scheduling", software_auto_scheduling_path, class: "text-base text-gray-500 hover:text-gray-900" %>
              </li>
            </ul>
          </div>
          <div class="mt-12 md:mt-0">
            <h3 class="text-sm font-semibold text-gray-400 tracking-wider uppercase">
              Industry
            </h3>
            <ul class="mt-4 space-y-4">
              <li>
                <%= link_to "Restaurants & Hospitality", industry_hospitality_path, class: "text-base text-gray-500 hover:text-gray-900" %>
              </li>
              <li>
                <%= link_to "Healthcare", industry_healthcare_path, class: "text-base text-gray-500 hover:text-gray-900" %>
              </li>
              <li>
                <%= link_to "Staffing", industry_staffing_path, class: "text-base text-gray-500 hover:text-gray-900" %>
              </li>
              <li>
                <%= link_to "Hotels", industry_hotels_path, class: "text-base text-gray-500 hover:text-gray-900" %>
              </li>
              <li>
                <%= link_to "Retail", industry_retail_path, class: "text-base text-gray-500 hover:text-gray-900" %>
              </li>
              <li>
                <%= link_to "Elder Care", industry_elderly_care_path, class: "text-base text-gray-500 hover:text-gray-900" %>
              </li>
              <li>
                <%= link_to "Hospitals", industry_hospitals_path, class: "text-base text-gray-500 hover:text-gray-900" %>
              </li>
            </ul>
          </div>
        </div>
        <div class="md:grid md:grid-cols-3 md:gap-8">
          <div>
            <h3 class="text-sm font-semibold text-gray-400 tracking-wider uppercase">
              Support
            </h3>
            <ul class="mt-4 space-y-4">
              <li>
                <%= link_to "Pricing", pricing_path, class: "text-base text-gray-500 hover:text-gray-900" %>
              </li>

              <li>
                <a href="https://help.tanda.co/en/" class="text-base text-gray-500 hover:text-gray-900">
                  Guides
                </a>
              </li>

              <li>
                <a href="https://my.tanda.co/api/v2/documentation" class="text-base text-gray-500 hover:text-gray-900">
                  API Docs
                </a>
              </li>
              <li>
                <%= link_to "Integrations", integrations_path, class: "text-base text-gray-500 hover:text-gray-900" %>
              </li>
            </ul>
          </div>
          <div class="mt-12 md:mt-0">
            <h3 class="text-sm font-semibold text-gray-400 tracking-wider uppercase">
              Company
            </h3>
            <ul class="mt-4 space-y-4">
              <li>
                <%= link_to "Contact Us", contact_us_path, class: "text-base text-gray-500 hover:text-gray-900" %>
              </li>

              <li>
                <%= link_to "News", news_path, class: "text-base text-gray-500 hover:text-gray-900" %>
              </li>

              <li>
                <%= link_to "Ebooks", whitepapers_path, class: "text-base text-gray-500 hover:text-gray-900" %>
              </li>
            </ul>
          </div>
          <div class="mt-12 md:mt-0">
            <h3 class="text-sm font-semibold text-gray-400 tracking-wider uppercase">
              Legal
            </h3>
            <ul class="mt-4 space-y-4">
              <li>
                <%= link_to "Cookies", cookies_path, class: "text-base text-gray-500 hover:text-gray-900" %>
              </li>

              <li>
                <%= link_to "Privacy Policy", privacy_policy_path, class: "text-base text-gray-500 hover:text-gray-900" %>
              </li>

              <li>
                <%= link_to "Terms", terms_path, class: "text-base text-gray-500 hover:text-gray-900" %>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="mt-8 border-t border-gray-200 pt-8 md:flex md:items-center md:justify-between">
      <div class="flex space-x-6 md:order-2">
        <%= link_to "https://www.facebook.com/Workforcedotcom/", class: "text-gray-400 hover:text-gray-500" do %>
          <span class="sr-only">Facebook</span>
          <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
            <path fill-rule="evenodd" d="M22 12c0-5.523-4.477-10-10-10S2 6.477 2 12c0 4.991 3.657 9.128 8.438 9.878v-6.987h-2.54V12h2.54V9.797c0-2.506 1.492-3.89 3.777-3.89 1.094 0 2.238.195 2.238.195v2.46h-1.26c-1.243 0-1.63.771-1.63 1.562V12h2.773l-.443 2.89h-2.33v6.988C18.343 21.128 22 16.991 22 12z" clip-rule="evenodd" />
          </svg>
        <% end %>
        <%= link_to "https://twitter.com/workforcedotcom", class: "text-gray-400 hover:text-gray-500" do %>
          <span class="sr-only">Twitter</span>
          <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
            <path d="M8.29 20.251c7.547 0 11.675-6.253 11.675-11.675 0-.178 0-.355-.012-.53A8.348 8.348 0 0022 5.92a8.19 8.19 0 01-2.357.646 4.118 4.118 0 001.804-2.27 8.224 8.224 0 01-2.605.996 4.107 4.107 0 00-6.993 3.743 11.65 11.65 0 01-8.457-4.287 4.106 4.106 0 001.27 5.477A4.072 4.072 0 012.8 9.713v.052a4.105 4.105 0 003.292 4.022 4.095 4.095 0 01-1.853.07 4.108 4.108 0 003.834 2.85A8.233 8.233 0 012 18.407a11.616 11.616 0 006.29 1.84" />
          </svg>
        <% end %>
        <%= link_to "http://linkedin.com/company/workforcemanagement", class: "text-gray-400 hover:text-gray-500" do %>
          <span class="sr-only">LinkedIn</span>
          <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
            <path xmlns="http://www.w3.org/2000/svg" d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z"/>
          </svg>
        <% end %>
        <%= link_to "https://www.youtube.com/channel/UCpDoOWR212YK3D_7Iyve3pQ", class: "text-gray-400 hover:text-gray-500" do %>
          <span class="sr-only">YouTube</span>
          <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
            <path d="M23.498 6.186a3.016 3.016 0 0 0-2.122-2.136C19.505 3.545 12 3.545 12 3.545s-7.505 0-9.377.505A3.017 3.017 0 0 0 .502 6.186C0 8.07 0 12 0 12s0 3.93.502 5.814a3.016 3.016 0 0 0 2.122 2.136c1.871.505 9.376.505 9.376.505s7.505 0 9.377-.505a3.015 3.015 0 0 0 2.122-2.136C24 15.93 24 12 24 12s0-3.93-.502-5.814zM9.545 15.568V8.432L15.818 12l-6.273 3.568z"/>
          </svg>
        <% end %>
      </div>
      <p class="mt-8 text-base text-gray-400 md:mt-0 md:order-1">
        &copy; <%= Time.now.year %> Workforce.com. All rights reserved.
      </p>
    </div>
  </div>
</footer>

app/views/layouts/_google_analytics.html.erb
<script>!function(w){var clearbit=w.clearbit=w.clearbit||[];if(!clearbit.initialize)if(clearbit.invoked)w.console&&console.error&&console.error("Clearbit snippet included twice.");else{clearbit.invoked=!0;clearbit.methods=["trackSubmit","trackClick","trackLink","trackForm","pageview","identify","reset","group","track","ready","alias","page","once","off","on"];clearbit.factory=function(t){return function(){var e=Array.prototype.slice.call(arguments);e.unshift(t);clearbit.push(e);return clearbit}};for(var t=0;t<clearbit.methods.length;t++){var e=clearbit.methods[t];clearbit[e]=clearbit.factory(e)}clearbit.load=function(t){var e=document.createElement("script");e.async=!0;e.src=("https:"===document.location.protocol?"https://":"http://")+"x.clearbitjs.com/v1/"+t+"/clearbit.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(e,n)};clearbit.SNIPPET_VERSION="3.1.0";    clearbit.load("pk_3da774b59a0834ff4225c3309aa150d2");    clearbit.page();  }}(window);</script>
<script async src="https://www.googletagmanager.com/gtag/js?id=<%= Rails.env.production? ? "G-P4PYCQ18Y2" : "G-0QQN6EMC6Y" %>"></script>
<script>
	window.dataLayer = window.dataLayer || [];
	function gtag(){dataLayer.push(arguments);}
	gtag('js', new Date());

	gtag('config', '<%= Rails.env.production? ? "G-P4PYCQ18Y2" : "G-0QQN6EMC6Y" %>');
	<% if Rails.env.production? %>
	  gtag('config', 'UA-902495-4');
	<% end %>
</script>

app/views/layouts/_hotjar.html.erb
<!-- Hotjar Tracking Code for https://www.workforce.com/ -->
<script>
    (function(h,o,t,j,a,r){
        h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
        h._hjSettings={hjid:1655573,hjsv:6};
        a=o.getElementsByTagName('head')[0];
        r=o.createElement('script');r.async=1;
        r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
        a.appendChild(r);
    })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
</script>

app/views/layouts/_pardot.html.erb
<script type="text/javascript">
piAId = '967793';
piCId = '42936';
piHostname = 'pi.pardot.com';

(function() {
	function async_load(){
		var s = document.createElement('script'); s.type = 'text/javascript';
		s.src = ('https:' == document.location.protocol ? 'https://pi' : 'http://cdn') + '.pardot.com/pd.js';
		var c = document.getElementsByTagName('script')[0]; c.parentNode.insertBefore(s, c);
	}
	if(window.attachEvent) { window.attachEvent('onload', async_load); }
	else { window.addEventListener('load', async_load, false); }
})();
</script>

app/views/layouts/_phone.html.erb
<svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
  <path d="M14.414 7l3.293-3.293a1 1 0 00-1.414-1.414L13 5.586V4a1 1 0 10-2 0v4.003a.996.996 0 00.617.921A.997.997 0 0012 9h4a1 1 0 100-2h-1.586z" />
  <path d="M2 3a1 1 0 011-1h2.153a1 1 0 01.986.836l.74 4.435a1 1 0 01-.54 1.06l-1.548.773a11.037 11.037 0 006.105 6.105l.774-1.548a1 1 0 011.059-.54l4.435.74a1 1 0 01.836.986V17a1 1 0 01-1 1h-2C7.82 18 2 12.18 2 5V3z" />
</svg>

app/views/layouts/_poa_modal.html.erb
<div class="fixed text-gray-500 flex items-center justify-center overflow-auto z-50 bg-black bg-opacity-40 left-0 right-0 top-0 bottom-0 hidden" data-poa-modal-target="bg" data-transition-enter="transition ease-out duration-300" data-transition-enter-start="transform opacity-0" data-transition-enter-end="transform opacity-100" data-transition-leave="z-30 transition ease-in duration-200" data-transition-leave-start="transform opacity-100" data-transition-leave-end="transform opacity-0 z-0" data-action="click->poa-modal#close">
  <div class="bg-white rounded-xl shadow-2xl p-6 sm:p-12 py-16 sm:py-20 sm:w-5/12 mx-3 sm:mx-10" data-poa-modal-target="panel" data-transition-enter="transition ease-out duration-300" data-transition-enter-start="transform opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95" data-transition-enter-end="transform opacity-100 translate-y-0 sm:scale-100" data-transition-leave="transition ease-in duration-200" data-transition-leave-start="transform opacity-100 translate-y-0 sm:scale-100" data-transition-leave-end="transform z-0 opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95">
	<%= turbo_frame_tag "poa", src: poa_path, loading: "lazy" %>
  </div>
</div>

app/views/layouts/_star.html.erb
<svg xmlns="http://www.w3.org/2000/svg" class="<%= custom_class %>" viewBox="0 0 20 20" fill="currentColor">
  <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
</svg>